import { useMemo, useState } from 'react';
import { ArrowRight, Check, Clock3, Search, Sprout, Volume2 } from 'lucide-react';
import type { Hanzi, Poem, Profile } from '../types';
import { completedCount } from '../store';

export function HanziLibrary({words,profile,onOpen,onSpeak}:{words:Hanzi[];profile:Profile;onOpen:(word:Hanzi)=>void;onSpeak:(text:string)=>void}){
  const [query,setQuery]=useState('');
  const [page,setPage]=useState(()=>{const w=words.find(w=>w.id===profile.lastActivity?.id);return w?Math.floor(words.indexOf(w)/50):0;});
  const [filter,setFilter]=useState('全部');
  const completed=completedCount(profile.hanzi);
  const filtered=useMemo(()=>words.filter(w=>(!query||`${w.char}${w.pinyin}${w.words.join('')}${w.meaning}`.includes(query))&&(filter==='全部'||(filter==='已过关'&&profile.hanzi[w.id]?.completed)||(filter==='待复习'&&profile.hanzi[w.id]?.completed&&profile.hanzi[w.id].reviewAt<=Date.now())||(filter==='未过关'&&!profile.hanzi[w.id]?.completed))),[words,query,filter,profile.hanzi]);
  const pages=Math.ceil(filtered.length/50),visible=filtered.slice(page*50,(page+1)*50);
  const searching=Boolean(query)||filter!=='全部';
  return <div className="library-page"><div className="page-heading"><div><span className="eyebrow"><Sprout size={16}/>从小小的发现，到大大的世界</span><h1>汉字小冒险</h1><p>每个字都有自己的故事，慢慢认识 1000 个朋友。</p></div><div className="library-total"><b>{completed}</b><span>/ 1000 个字</span></div></div><div className="course-ribbon"><span>① 生活启蒙 · 前100字</span><span>② 常用表达 · 101—500字</span><span>③ 阅读进阶 · 501—1000字</span></div><div className="library-tools"><div className="filter-tabs">{['全部','未过关','已过关','待复习'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>{setFilter(f);setPage(0);}}>{f}</button>)}</div><label className="search-box"><Search size={18}/><input value={query} aria-label="搜索汉字" placeholder="找一个字、拼音或词语" onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div><div className="hanzi-course">{Array.from({length:Math.ceil(visible.length/10)},(_,i)=>{const group=visible.slice(i*10,(i+1)*10);return <section className="word-group" key={i}><div className="word-group-heading"><span>{searching?'找到的汉字朋友':`第 ${Math.floor(words.indexOf(group[0])/10)+1} 站`}</span><h3>{searching?'认识你的新朋友':group[0]?.theme}</h3><span className="muted">{searching?'选一个字，听听它的故事':'认识10个字，迎接新动物'}</span></div><div className="word-grid">{group.map(w=>{const p=profile.hanzi[w.id],due=p?.completed&&p.reviewAt<=Date.now();return <button key={w.id} className={`word-tile ${p?.completed?'mastered':''} ${p&&!p.completed?'in-progress':''}`} onClick={()=>onOpen(w)} aria-label={`学习${w.char}字${p?.completed?'，已过关':''}`}><span className="word-tile-icon">{w.icon}</span><b>{w.char}</b><small>{w.pinyin}</small><span className="word-status">{due?<Clock3 size={14}/>:p?.completed?<Check size={14}/>:p?<span className="progress-dot"/>:null}{due?'复习':p?.completed?'已过关':p?'继续':'出发'}</span></button>;})}</div></section>;})}</div>{!visible.length&&<div className="empty-note">这片小岛上暂时没有找到这个字，换个词试试。</div>}<div className="pagination"><button className="pill-button" disabled={page===0} onClick={()=>{setPage(p=>p-1);window.scrollTo(0,0);}}>上一片小岛</button><span>{page+1} / {Math.max(1,pages)}</span><button className="pill-button" disabled={page>=pages-1} onClick={()=>{setPage(p=>p+1);window.scrollTo(0,0);}}>下一片小岛<ArrowRight size={18}/></button></div><p className="muted small library-tip"><Volume2 size={16}/>进入每个字后，可以点小喇叭听字音与拼音。<button className="text-button" onClick={()=>onSpeak('每个字都是一个新朋友，先玩一玩，再认识它。')}>听小提示</button></p></div>;
}
export function PoemLibrary({poems,profile,onOpen}:{poems:Poem[];profile:Profile;onOpen:(poem:Poem)=>void}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('全部'),[page,setPage]=useState(0);
  const [level,setLevel]=useState('全部难度');
  const filtered=poems.filter(p=>(!query||`${p.title}${p.author}${p.lines.join('')}`.includes(query))&&(filter==='全部'||filter===p.dynasty||filter===p.theme)&&(level==='全部难度'||(level==='短篇启蒙'&&p.level===1)||(level==='亲子进阶'&&p.level>1)));
  const themes=[...new Set(poems.map(p=>p.theme))].slice(0,6);
  const visible=filtered.slice(page*12,(page+1)*12),pages=Math.ceil(filtered.length/12);
  return <div className="library-page poetry-library"><div className="page-heading"><div><span className="eyebrow">🌼 在心里，种下一首诗</span><h1>诗词花园</h1><p>听见古人的故事，发现今天的美好。</p></div><div className="library-total"><b>{completedCount(profile.poems)}</b><span>/ 300 首诗词</span></div></div><div className="poetry-banner"><div><span className="mini-label">给小朋友的第一首诗</span><h2>诗里的月亮，<br/>和今晚的一样亮。</h2><p>听、看、读、懂，一起走进唐诗宋词。</p></div><div className="poetry-banner-art">🌙<span>山</span><i>月</i></div></div><div className="library-tools"><div className="filter-tabs">{['全部','唐','宋',...themes].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>{setFilter(f);setPage(0);}}>{f==='唐'?'唐诗':f==='宋'?'宋词':f}</button>)}</div><label className="search-box"><Search size={18}/><input placeholder="找诗名、诗人或一句诗" aria-label="搜索诗词" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div><div className="poem-filter-row"><select aria-label="诗词难度" value={level} onChange={e=>{setLevel(e.target.value);setPage(0);}}>{['全部难度','短篇启蒙','亲子进阶'].map(v=><option key={v}>{v}</option>)}</select><span className="muted small">共 {filtered.length} 首 · 长篇适合家长陪伴赏读</span></div><div className="poem-card-grid">{visible.map((p,i)=><button className={`poem-card color-${i%4}`} key={p.id} onClick={()=>onOpen(p)}><div className="poem-card-top"><span>{p.icon}</span><small>{p.level===1?'短篇启蒙':'亲子进阶'}</small></div><h2>{p.title}</h2><span className="poem-author">{p.dynasty} · {p.author}</span><p>{p.lines[0]}</p><div className="poem-card-bottom"><span>{profile.poems[p.id]?.completed?<><Check size={14}/>已过关</>:profile.poems[p.id]?'继续学习':p.theme}</span><ArrowRight size={20}/></div></button>)}</div>{!visible.length&&<div className="empty-note">换一个关键词，再找找花园里的诗。</div>}<div className="pagination"><button className="pill-button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page+1} / {Math.max(1,pages)}</span><button className="pill-button" disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)}>下一页<ArrowRight size={18}/></button></div></div>;
}
