import { useState } from 'react';
import { Check, Download, FileJson, Plus, ShieldCheck, Upload } from 'lucide-react';
import type { Profile, SaveData } from '../types';
import type { MusicStatus } from '../music-engine';
import MusicControls from './MusicControls';
import { completedCount, createProfile, dueLessons, validateSave } from '../store';

export function downloadJSON(value: unknown, name: string) {
  const blob = new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'});
  const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function Parents({data,profile,onReplace,onUpdate,saveError,corrupted,onResumeSave,musicStatus,onMusicStart}:{musicStatus:MusicStatus;onMusicStart:()=>void;data:SaveData;profile:Profile;onReplace:(data:SaveData)=>void;onUpdate:(updater:(p:Profile)=>Profile)=>void;saveError:string;corrupted?:string;onResumeSave:()=>void}){
  const [name,setName]=useState('');
  const [avatar,setAvatar]=useState('🐰');
  const [message,setMessage]=useState('');
  const [imported,setImported]=useState<SaveData|null>(null);
  const completedHanzi=completedCount(profile.hanzi),completedPoems=completedCount(profile.poems);
  async function importFile(file:File){
    if(file.size>10_000_000){setMessage('文件太大，请使用从本游戏导出的 JSON 存档。');return;}
    try {const json=JSON.parse(await file.text());if(!validateSave(json)){setMessage('文件格式不完整或版本不匹配，现有档案未改动。');return;}setImported(json);setMessage(`检测到 ${json.profiles.length} 个档案，确认后将恢复备份中的进度。`);}catch{setMessage('这个文件无法读取，现有档案未改动。');}
  }
  return <div className="parents-page"><div className="page-heading"><div><span className="eyebrow"><ShieldCheck size={16}/>陪伴，比学得快更重要</span><h1>家长小屋</h1><p>按孩子的兴趣安排节奏，保存每一次小小的成长。</p></div><span className="local-badge"><ShieldCheck size={16}/>档案保存在本机</span></div>
    <div className="parent-overview"><div><b>{completedHanzi}<small> / 1000</small></b><span>已过关汉字</span></div><div><b>{completedPoems}<small> / 300</small></b><span>已过关诗词</span></div><div><b>{dueLessons(profile).length}</b><span>今天可以再复习</span></div><div><b>{Object.keys(profile.zoo.animals).length}</b><span>动物朋友</span></div></div>
    <div className="parent-columns"><section className="panel"><h2>孩子的学习节奏</h2><label>昵称<input aria-label="当前儿童昵称" value={profile.name} maxLength={16} onChange={e=>onUpdate(p=>({...p,name:e.target.value||'小小探险家'}))}/></label><label>每天认识几个新字<select value={profile.settings.dailyGoal} onChange={e=>onUpdate(p=>({...p,settings:{...p.settings,dailyGoal:Number(e.target.value)}}))}>{[1,2,3,5,8,10].map(n=><option key={n} value={n}>{n} 个</option>)}</select></label><label>连续使用多久提醒休息<select value={profile.settings.sessionMinutes} onChange={e=>onUpdate(p=>({...p,settings:{...p.settings,sessionMinutes:Number(e.target.value)}}))}>{[5,10,15,20,30].map(n=><option key={n} value={n}>{n} 分钟</option>)}</select></label><label>朗读速度<select value={profile.settings.speechRate} onChange={e=>onUpdate(p=>({...p,settings:{...p.settings,speechRate:Number(e.target.value)}}))}><option value={.65}>更慢一些</option><option value={.8}>慢慢读（默认）</option><option value={1}>自然速度</option></select></label><MusicControls enabled={profile.settings.music ?? true} volume={profile.settings.musicVolume ?? .22} sound={profile.settings.sound} status={musicStatus} onStart={onMusicStart} onEnabledChange={music=>onUpdate(p=>({...p,settings:{...p.settings,music}}))} onVolumeChange={musicVolume=>onUpdate(p=>({...p,settings:{...p.settings,musicVolume}}))}/><p className="parent-advice">3 岁起步，先看图、听故事、说生活里的词，再认识字形。1000 字和 300 首诗词是长期内容库，不是当前年龄的达标要求。</p></section>
    <section className="panel"><h2>每个孩子，都有自己的小岛</h2><div className="profile-list">{data.profiles.map(p=><button key={p.id} className={`profile-row ${p.id===data.activeId?'active':''}`} onClick={()=>onReplace({...data,activeId:p.id})}><span className="profile-avatar">{p.avatar}</span><span><b>{p.name}</b><small>{completedCount(p.hanzi)} 字 · {completedCount(p.poems)} 首诗词</small></span>{p.id===data.activeId&&<Check size={20}/>}</button>)}</div><div className="new-profile"><h3>新增儿童档案</h3><div className="avatar-picker">{['🐰','🐼','🦊','🐨','🐯','🐧'].map(a=><button key={a} className={avatar===a?'selected':''} onClick={()=>setAvatar(a)} aria-label={`选择${a}头像`}>{a}</button>)}</div><input placeholder="给小探险家取个名字" aria-label="新儿童昵称" value={name} maxLength={16} onChange={e=>setName(e.target.value)}/><button className="pill-button" disabled={!name.trim()||data.profiles.length>=20} onClick={()=>{const p=createProfile(name,avatar);onReplace({...data,activeId:p.id,profiles:[...data.profiles,p]});setName('');setMessage('新的小岛准备好啦，每个孩子的进度独立保存。');}}><Plus size={18}/>创建小岛</button></div></section></div>
    <section className="panel backup-panel"><div><span className="eyebrow"><FileJson size={16}/>留一份成长纪念</span><h2>备份与恢复</h2><p>同一浏览器、同一网页地址会恢复本机进度。清除浏览器数据或换设备前，请导出备份。</p></div><div className="backup-actions"><button className="pill-button" onClick={()=>downloadJSON(data,`字游小岛-成长备份-${new Date().toLocaleDateString('sv-SE')}.json`)}><Download size={19}/>导出全部档案</button><label className="pill-button file-input-label"><Upload size={19}/>导入备份<input type="file" accept="application/json,.json" onChange={e=>{if(e.target.files?.[0])void importFile(e.target.files[0]);e.target.value='';}}/></label></div>{message&&<p className="backup-message" role="status">{message}</p>}{imported&&<div className="import-confirm"><p>将恢复 {imported.profiles.map(p=>p.name).join('、')} 的档案。现有档案会先导出，方便撤回。</p><button className="primary-button" onClick={()=>{downloadJSON(data,'字游小岛-导入前备份.json');onReplace(imported);setImported(null);setMessage('已恢复备份，请继续你的冒险。');}}>确认恢复这份备份<Check size={18}/></button><button className="text-button" onClick={()=>setImported(null)}>保留现有档案</button></div>}{saveError&&<div className="save-recovery"><p>{saveError}</p>{corrupted&&<button className="pill-button" onClick={()=>downloadJSON(corrupted,'字游小岛-原始存档.json')}><Download size={18}/>导出原始存档</button>}<button className="pill-button" onClick={()=>{if(corrupted)downloadJSON(corrupted,'字游小岛-恢复前原始存档.json');onResumeSave();}}>恢复保存当前档案</button></div>}</section>
    <section className="panel content-disclosure"><h2>课程说明与内容校订</h2><p>本项目按洪恩公开的“玩、认、练、写、说”教学流程设计，采用原创界面与动物角色。不是洪恩官方产品。</p><p>目前数据源与内容编辑状态列在项目文档中。标为待复核的诗词解读需家长陪读；没有可靠写作年代、地点的作品明确说明背景不详。跟读与背诵由家长确认，游戏不声称自动判断发音是否准确。</p><a href="/docs/SPEC.md" target="_blank" rel="noreferrer">查看产品规格</a></section>
  </div>;
}
